drop
extension if exists "pg_net";

create table "public"."users"
(
    "id"         bigint generated by default as identity not null,
    "created_at" timestamp with time zone                not null default now(),
    "email"      text                                    not null,
    "first_name" text                                    not null,
    "last_name"  text                                    not null
);

alter table "public"."users" enable row level security;

create unique index user_info_pkey on public.users using btree (id);

alter table "public"."users"
    add constraint "user_info_pkey" primary key using index "user_info_pkey";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant
truncate
on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant
truncate
on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant
truncate
on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


